sonar.projectKey=mi-microservicio
sonar.projectName=Mi Microservicio
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/*_test.py,**/tests/**,**/venv/**
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
