sonar.organization=yuliet719-beep
sonar.projectKey=yuliet719-beep_mi-microservicio
sonar.projectName=Mi Microservicio
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/venv/**,**/__pycache__/**
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
