apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mi-chart.fullname" . }}
  labels:
    {{- include "mi-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mi-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mi-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mi-microservicio
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 20
