apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-microservicio
  labels:
    app: mi-microservicio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-microservicio
  template:
    metadata:
      labels:
        app: mi-microservicio
    spec:
      containers:
        - name: mi-microservicio
          image: yulietrojas/mi-microservicio:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
