name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalación de dependencias
        run: |
          pip install -r app/requirements.txt
          pip install -r requirements-dev.txt

      - name: Ejecución de pruebas
        run: pytest tests/ -v

      - name: Análisis estático de código (flake8)
        run: flake8 app/ --max-line-length=100 --extend-ignore=E203,W503
