replicaCount: 1

image:
  repository: yulietrojas/mi-microservicio
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

containerPort: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
